# SPDX-License-Identifier: GPL-3.0-only
"""python tools/generate_camera_catalog.py [--check]"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / "camera_catalog.json").read_text(encoding="utf-8"))
text = "// Generated by tools/generate_camera_catalog.py; edit camera_catalog.json.\n"
text += "export const CAMERA_CATALOG = " + json.dumps(catalog, ensure_ascii=False, indent=2) + ";\n"
text += """export const CAMERA_MOTIONS = Object.freeze(Object.fromEntries(CAMERA_CATALOG.motions.map(item => [item.value, Object.freeze(item)])));
export const MOTION_LABELS = Object.freeze(Object.fromEntries(CAMERA_CATALOG.motions.map(item => [item.value, item.label])));
export const motionChoices = (neutral = "", label = "Unspecified") => [[neutral, label], ...CAMERA_CATALOG.motions.map(item => [item.value, item.label])];
export const frameChoices = key => [["", "Unspecified"], ...CAMERA_CATALOG.frameEnums[key].map(value => [value, CAMERA_CATALOG.frameLabels[key][value]])];
export const VISUAL_CAMERA_MOTIONS = Object.freeze([...new Set(CAMERA_CATALOG.motions.map(item => item.group))].map(label => ({label, items: CAMERA_CATALOG.motions.filter(item => item.group === label).map(item => [item.value, item.label, item.icon])})));
"""
outputs = {ROOT / "web/studio/camera_catalog.js": text}
for name in ["cinematography_v2", "shot_plan_v2"]:
    path = ROOT / "docs/schemas" / (name + ".schema.json")
    source = path.read_text(encoding="utf-8")

    def replace_enum(match):
        values = (["none"] if match.group(2) == "cameraMotion" else []) + [
            item["value"] for item in catalog["motions"]
        ]
        return match.group(1) + json.dumps(values)

    source = re.sub(r'("(cameraMotion|motionType)"\s*:\s*\{\s*"enum"\s*:\s*)\[[^\]]*\]', replace_enum, source)
    outputs[path] = source

for path, content in outputs.items():
    if "--check" in sys.argv:
        if path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"Stale camera artifact: {path.relative_to(ROOT)}")
    else:
        path.write_text(content, encoding="utf-8")
